Repository revealapp/Revert, pull requests merged in 2020-08, with the labels that each got.

#58 Color assets catalogue
  Revert.xcodeproj/project.pbxproj
  Revert/Resources/Colors.xcassets/AwesGreen.colorset/Contents.json
  Revert/Resources/Colors.xcassets/Contents.json
  Revert/Resources/Colors.xcassets/GraySelection.colorset/Contents.json
  Revert/Resources/Colors.xcassets/RevertDarkBlue.colorset/Contents.json
  Revert/Resources/Colors.xcassets/RevertLightBlack.colorset/Contents.json
  Revert/Resources/Colors.xcassets/RevertOrange.colorset/Contents.json
  Revert/Resources/Colors.xcassets/RevertPink.colorset/Contents.json
  Revert/Resources/Colors.xcassets/RevertTint.colorset/Contents.json
  Revert/Resources/Colors.xcassets/VividGreen.colorset/Contents.json
  Revert/Resources/Colors.xcassets/whiteSmoke.colorset/Contents.json
  Revert/Sources/AppDelegate.swift
  Shared/Sources/AutoLayoutGuidesViewController.swift
  Shared/Sources/AutoResizingMaskViewSource.swift
  Shared/Sources/CollectionViewCells.swift
  Shared/Sources/CollectionViewController.swift
  Shared/Sources/CountriesViewController.swift
  Shared/Sources/DeepView.swift
  Shared/Sources/LayerPropertiesCells.swift
  Shared/Sources/MapViewController.swift
  Shared/Sources/TableViewCells.swift
  Shared/Sources/UIColor+Revert.swift
Labels: Enhancement

#59 Use Decodable for `HomeItem` model class
  Revert-tvOS/Sources/CollectionDataSource.swift
  Revert-tvOS/Sources/HomeCollectionViewController.swift
  Revert-tvOS/Sources/HomeViewController.swift
  Revert-tvOS/Sources/Person.swift
  Revert-tvOS/Sources/SearchViewController.swift
  Revert-tvOS/Sources/WhatsNewViewController.swift
  Revert.xcodeproj/project.pbxproj
  Revert/Sources/HomeViewController.swift
  Shared/Resources/Data/HomeCollectionItems.plist
  Shared/Resources/Data/HomeItems_iOS.plist
  Shared/Resources/Data/HomeItems_tvOS.plist
  Shared/Resources/Data/NewItems_tvOS.plist
  Shared/Resources/Data/Persons.plist
  Shared/Sources/HomeItem.swift
  Shared/Sources/HomeSection.swift
  Shared/Sources/NewDataSource.swift
  Shared/Sources/RevertItems.swift
  Shared/Sources/RevertSection.swift
Labels: Enhancement, Needs Review

#61 Fix tvOS app crash when loading scenario from Example segment.
  Revert-tvOS/Sources/HomeCollectionViewController.swift
Labels: Crash

#62 Convert all model objects to `Decodable` and get rid of legacy codes
  Revert-tvOS/Sources/HomeCollectionViewController.swift
  Revert-tvOS/Sources/HomeViewController.swift
  Revert-tvOS/Sources/SearchViewController.swift
  Revert-tvOS/Sources/WhatsNewViewController.swift
  Revert.xcodeproj/project.pbxproj
  Revert/Sources/HomeViewController.swift
  Revert/Sources/PickerViewController.swift
  Shared/Sources/AlertViewController.swift
  Shared/Sources/Collectable.swift
  Shared/Sources/CollectableCollection.swift
  Shared/Sources/CollectableGroup.swift
  Shared/Sources/ControlsDataSource.swift
  Shared/Sources/ControlsViewController.swift
  Shared/Sources/CountriesViewController.swift
  Shared/Sources/Country.swift
  Shared/Sources/DataSource.swift
  Shared/Sources/Item.swift
  Shared/Sources/ItemSection.swift
  Shared/Sources/MapAnnotationView.swift
  Shared/Sources/MapLocationItem.swift
  Shared/Sources/MapViewController.swift
  Shared/Sources/NewDataSource.swift
  Shared/Sources/Requirement.swift
  Shared/Sources/RevertItems.swift
Labels: Enhancement

#67 Replace fileprivate -> private
  Revert-tvOS/Sources/SearchViewController.swift
  Revert/Sources/WebViewController.swift
  Shared/Sources/AlertViewController.swift
  Shared/Sources/AutoLayoutMarginsViewController.swift
  Shared/Sources/CollectionViewCells.swift
  Shared/Sources/ControlsViewController.swift
  Shared/Sources/CountriesViewController.swift
  Shared/Sources/MapViewController.swift
  Shared/Sources/OpenGLViewController.swift
  Shared/Sources/RevealOpenGLCube.swift
  Shared/Sources/RevertItems.swift
Labels: Enhancement

#68 Add context menu to ControlsViewController
  Revert/Resources/Base.lproj/Controls.storyboard
  Shared/Resources/Data/ControlItems_iOS.plist
  Shared/Sources/ControlsViewController.swift
Labels: Enhancement
